# Generated by Django 5.0.7 on 2024-08-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cohort',
            field=models.CharField(blank=True, choices=[('Cohort 1', 'Cohort 1'), ('Cohort 2', 'Cohort 2'), ('Cohort 3', 'Cohort 3'), ('Cohort 4', 'Cohort 4'), ('Cohort 5', 'Cohort 5'), ('Cohort 6', 'Cohort 6'), ('Cohort 7', 'Cohort 7'), ('Cohort 8', 'Cohort 8'), ('Cohort 9', 'Cohort 9'), ('Cohort 10', 'Cohort 10')], max_length=20, null=True),
        ),
    ]
