# Generated by Django 5.0.7 on 2024-08-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('profiles', '0002_alter_profile_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assigned_paths',
            field=models.ManyToManyField(blank=True, related_name='students', to='content.path'),
        ),
    ]
