# Generated by Django 5.0.7 on 2024-08-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
