# Generated by Django 5.0.7 on 2024-08-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_daily_streak_profile_last_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.TextField(default='[]'),
        ),
    ]
