# Generated by Django 5.0.7 on 2024-08-05 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_studentprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentprogress',
            unique_together={('student', 'lesson')},
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.module'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='path',
        ),
    ]
