# Generated by Django 5.0.7 on 2024-08-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_studentprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='module',
        ),
        migrations.AddField(
            model_name='lesson',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='content.module'),
        ),
    ]
