# Generated by Django 5.0.7 on 2024-08-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_lesson_module_lesson_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='modules',
        ),
        migrations.AddField(
            model_name='module',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='modules', to='content.lesson'),
        ),
    ]
