# Generated by Django 5.0.7 on 2024-08-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_lesson_modules_module_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprogress',
            name='module',
        ),
        migrations.AddField(
            model_name='lesson',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='lesson_modules', to='content.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='module_lessons', to='content.lesson'),
        ),
    ]
