# Generated by Django 5.0.7 on 2024-08-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_studentprogress_module_lesson_modules_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='modules',
        ),
        migrations.AlterField(
            model_name='module',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='modules', to='content.lesson'),
        ),
    ]
