# Generated by Django 5.0.7 on 2024-08-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_lesson_modules_alter_module_lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('incorrect_answer_1', models.CharField(max_length=255)),
                ('incorrect_answer_2', models.CharField(blank=True, max_length=255, null=True)),
                ('incorrect_answer_3', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='passing_percentage',
            field=models.PositiveIntegerField(blank=True, default=70, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='time_to_complete',
            field=models.PositiveIntegerField(default=10, verbose_name='Time to Complete (Minutes)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(blank=True, choices=[('text', 'Text Based'), ('video', 'Video Based'), ('quiz', 'Quiz/Assessment'), ('deliverable', 'Deliverable')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='path',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_questions',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='content.question'),
        ),
    ]
