# Generated by Django 5.0.7 on 2024-08-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_module_name_alter_path_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='path',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
